name: Test and Build Pipeline

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            # Images frontend y backend
            - name: Build Backend Docker image
              run: docker build --progress=plain -f build/backend.Dockerfile -t marsalsans/ci-cd-backend:latest .
            - name: Build Frontend Docker image
              run: docker build --progress=plain -f build/frontend.Dockerfile -t marsalsans/ci-cd-frontend:latest .

            - name: Launch CI environment
              run: |
                  docker compose -f docker-compose-ci.yml down
                  docker compose -f docker-compose-ci.yml up -d
            - name: Wait for CI environment is healthy
              run: build/scripts/wait-for-ci.sh
