name: Deploy CI

on:
    push:
        branches:
            - production

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'

            - name: Log in to Docker Hub
              run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Pull Docker image
              run: |
                  docker pull marsalsans/ci-cd-backend

            - name: Pull Docker image
              run: |
                  docker pull marsalsans/ci-cd-frontend

            - name: Deploy to Netlify
              uses: netlify/actions/cli@v1
              with:
                  args: deploy --prod --docker YOUR_BACKEND_IMAGE:latest YOUR_FRONTEND_IMAGE:latest
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
