name: SSH Connection

on:
    push:
        branches:
            - production

jobs:
    connect-ssh:
        runs-on: ubuntu-latest
        steps:
            - name: Connect via SSH
              uses: appleboy/ssh-action@master
              with:
                  host: direct.labs.play-with-docker.com
                  username: ip172-18-0-43-cpalubol2o9000dlcm70
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  debug: true
                  script: |
                      cd ci-cd-example
                      docker-compose -f docker-compose-deploy.yml down
                      git pull
                      docker-compose -f docker-compose-deploy.yml up -d --force-recreate
