name: Deploy to Server

on:
    push:
        branches:
            - production

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: SSH into server and execute commands
              run: |
                  ssh -o StrictHostKeyChecking=no ip172-18-0-43-cpalubol2o9000dlcm70@direct.labs.play-with-docker.com 'cd /ruta/a/tu/proyecto && docker-compose -f docker-compose-deploy.yml down && git pull && docker-compose -f docker-compose-deploy.yml up -d'
