name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # Agrega este paso para habilitar la depuración
            - name: Debug
              env:
                  CI: true
              run: |
                  echo "Current directory: $PWD"
                  echo "List of files: $(ls -la)"
                  echo "Environment variables: $(env)"

            - name: SSH into server and deploy
              uses: appleboy/ssh-action@master
              with:
                  host: 'direct.labs.play-with-docker.com'
                  username: 'ip172-18-0-43-cpalubol2o9000dlcm70'
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: '8022'
                  script: |
                      cd ci-cd-example
                      docker-compose -f docker-compose-deploy.yml down
                      git pull
                      docker-compose -f docker-compose-deploy.yml up -d
