name: SSH Connection

on:
    push:
        branches:
            - production

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up SSH key
              run: |
                  env
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub

                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -p 22 direct.labs.play-with-docker.com >> ~/.ssh/known_hosts
            - name: Deploy to server
              run: |
                  ssh -vvv ip172-18-0-50-cpareaol2o900080qfr0@direct.labs.play-with-docker.com "bash /root/ci-cd-example/build/scripts/deploy.sh"
