name: SSH Connection

on:
    push:
        branches:
            - production

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up SSH key
              run: |
                  env
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -p 22 direct.labs.play-with-docker.com >> ~/.ssh/known_hosts

            - name: Deploy to server
              run: |
                  scp build/scripts/deploy.sh ip172-18-0-50-cpareaol2o900080qfr0@direct.labs.play-with-docker.com:/tmp/deploy.sh
                  ssh ip172-18-0-50-cpareaol2o900080qfr0@direct.labs.play-with-docker.com "chmod +x /tmp/deploy.sh"
                  ssh -n -vvv -o StrictHostKeyChecking=no ip172-18-0-50-cpareaol2o900080qfr0@direct.labs.play-with-docker.com "bash /tmp/deploy.sh"
