name: Build and Test

on:
    push:
        branches:
            - production

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'

            - name: Log in to Docker Hub
              run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
                  
            - name: Pull Docker image
              run: |
                docker pull marsalsans/ci-cd-test

            - name: Run Docker container
              run: docker run -d --name mycontainer marsalsans/ci-cd-test

            - name: Copy files from Docker container
              run: docker cp mycontainer:/dist ./build

            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v1.1
              with:
                publish-dir: ./build
                production-deploy: true
              env:
                NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
