name: SSH Connection

on:
    push:
        branches:
            - main

jobs:
    connect-ssh:
        runs-on: ubuntu-latest
        steps:
            - name: Connect via SSH
              uses: appleboy/ssh-action@master
              with:
                  host: direct.labs.play-with-docker.com
                  username: ip172-18-0-43-cpalubol2o9000dlcm70
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: whoami
